### PR TITLE
WP media box fixes

### PR DESCRIPTION
**Pull request by newash**
Hello!

Before I wanted to update to your latest version with the shiny new WP media box integration I ran a few tests... and it wasn't producing the same output as the old button.

However I probably haven't checked with all the possible settings, for me with these changes now, it **does** produce the same HTML string. So I would still consider this as "beta", though you haven't mentioned beta in your release log for this.

Best regards,
newash

### CODE REVIEW

**Comment by newash** [comment]
...oh, and I've also fixed 2 typos (in `media-upload_search.php` and the last change in `media-views.js`)

**Comment by newash** [comment]
Bump!

**Comment by fukata** [comment]
@newash Sorry, too much late reply.
this issue still have problem?

**Comment by newash** [comment]
Thanks, honestly I don't know.
Haven't updated your plugin in my system since, I'll take a look later.

**Pull request closed without merging**
